# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TPMailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='tpmailers_user_related', related_query_name='tpmailers_user', to='TPMailer.Confirmation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
